food/urls.py
from django.urls import path
from food.views import *
app_name='foodies'

urlpatterns = [
    path('sweet/',sweet,name='sweet'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import food ,travel
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('travel/',include('travel.urls')),
]

travel/urls.py
from django.urls import path
from travel.views import *
app_name='travelling'

urlpatterns = [
    path('bihar/',bihar,name='bihar'),
]

food/models.py
from django.db import models

# Create your models here.

travel/models.py
from django.db import models

# Create your models here.

food/views.py
from django.shortcuts import render

def sweet(request):
    return render(request,'sweet.html')

travel/views.py
from django.shortcuts import render

def bihar(request):
    return render(request,'bihar.html')

templates/bihar.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <center>
            <h1> hii  Bihar </h1>
            <a href="{% url 'foodies:sweet' %}"> go to sweet name list  </a>
        </center>
    </body>
</html>

templates/sweet.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <center>
            <h1> hii sweet   </h1>
            <a href=" {% url 'travelling:bihar' %}"> back to great BIHAR </a>
        </center>
    </body>
</html>